# Generated by Django 4.2 on 2025-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_appuser_avatar_appuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_user.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='job',
            field=models.CharField(blank=True, max_length=100, verbose_name='job'),
        ),
    ]
